version: "3.8"

services: 
  mysqldb:
    image: mysql:latest
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT

  eureka-server:
    image: eureka-server:0.1
    ports:
      - 8761:8761
  user-service:
    image: user-service:0.1
    depends_on:
      - mysqldb
    restart: on-failure
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    environment: 
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url" : "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE",
        "spring.datasource.username" : "$MYSQLDB_USER",
        "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
        "spring.jpa.hibernate.ddl-auto" : "update",
        "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.MySQL8Dialect",
        "spring.jpa.show-sql" : "true",
        "spring.application.name":"user-service",
        "eureka.client.serviceUrl.defaultZone":"http://eureka-server:8761/eureka"
        }'

  product-service:
    image: product-service:0.1
    depends_on:
      - mysqldb
    restart: on-failure
    env_file: ./.env
    ports:
      - 9002:9002
    environment: 
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url" : "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE",
        "spring.datasource.username" : "$MYSQLDB_USER",
        "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
        "spring.jpa.hibernate.ddl-auto" : "update",
        "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.MySQL8Dialect",
        "spring.jpa.show-sql" : "true",
        "spring.application.name":"product-service",
        "eureka.client.serviceUrl.defaultZone":"http://eureka-server:8761/eureka"
        }'
    stdin_open: true
    tty: true
    
 
  
 
          
      
      